task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 1
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/sard/images/train
    ann_file: ./data/sard/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  drop_last: True
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/sard/images/val
    ann_file: ./data/sard/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction
