task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 10
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/visdrone2019/train/images
    ann_file: ./data/visdrone2019/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  drop_last: True
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./data/visdrone2019/val/images
    ann_file: ./data/visdrone2019/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction
